### ISSUE TITLE
spyder 4.0.1 installation fails

### ISSUE THREAD

**Issue by yt87** [conda-forge/spyder-feedstock#72]
Issue:

Cannot install spyder. Steps taken:

```
$ conda create --name spyder python=3.8 
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/gtrojan/miniconda3/envs/spyder

  added / updated specs:
    - python=3.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ld_impl_linux-64-2.33.1    |       h53a641e_8         589 KB  conda-forge
    pip-20.0.2                 |           py38_1         1.9 MB  conda-forge
    python-3.8.1               |       h357f687_2        58.2 MB  conda-forge
    wheel-0.34.2               |           py38_0          43 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        60.7 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-0_gnu
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.11.28-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2019.11.28-py38_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.33.1-h53a641e_8
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1006
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgomp            conda-forge/linux-64::libgomp-9.2.0-h24d8f2e_2
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  openssl            conda-forge/linux-64::openssl-1.1.1d-h516909a_0
  pip                conda-forge/linux-64::pip-20.0.2-py38_1
  python             conda-forge/linux-64::python-3.8.1-h357f687_2
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  setuptools         conda-forge/linux-64::setuptools-45.1.0-py38_0
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  wheel              conda-forge/linux-64::wheel-0.34.2-py38_0
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006


Proceed ([y]/n)? y


Downloading and Extracting Packages
pip-20.0.2           | 1.9 MB    | ######################################## | 100% 
python-3.8.1         | 58.2 MB   | ######################################## | 100% 
ld_impl_linux-64-2.3 | 589 KB    | ######################################## | 100% 
wheel-0.34.2         | 43 KB     | ######################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate spyder
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) [gtrojan@asok core]$ conda activate spyder
(spyder) [gtrojan@asok core]$ conda install spyder
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed    
 # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 1316, in solve
        raise UnsatisfiableError({})
    conda.exceptions.UnsatisfiableError: 
    Did not find conflicting dependencies. If you would like to know which
    packages conflict ensure that you have enabled unsatisfiable hints.
    
    conda config --set unsatisfiable_hints True
                
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 299, in install
        should_retry_solve=(repodata_fn != repodata_fns[-1]),
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 1318, in solve
        self.find_conflicts(specs, specs_to_add, history_specs)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 347, in find_conflicts
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 507, in build_conflict_map
        root, search_node, dep_graph, num_occurances)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 369, in breadth_first_search_for_dep_graph
        last_spec = MatchSpec.union((path[-1], target_paths[-1][-1]))[0]
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 481, in union
        return cls.merge(match_specs, union=True)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 475, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 475, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 502, in _merge
        final = this_component.union(that_component)
      File "/home/gtrojan/miniconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 764, in union
        return '|'.join(options)
    TypeError: sequence item 0: expected str instance, Channel found

`$ /home/gtrojan/miniconda3/bin/conda install spyder`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=spyder
                CONDA_EXE=/home/gtrojan/miniconda3/bin/conda
             CONDA_PREFIX=/home/gtrojan/miniconda3/envs/spyder
           CONDA_PREFIX_1=/home/gtrojan/miniconda3
    CONDA_PROMPT_MODIFIER=(spyder)
         CONDA_PYTHON_EXE=/home/gtrojan/miniconda3/bin/python
               CONDA_ROOT=/home/gtrojan/miniconda3
              CONDA_SHLVL=2
          LD_LIBRARY_PATH=/usr/local/netcdf-4.6.1/lib:/usr/local/cuda/lib64:/usr/local/lib64
             LIBRARY_PATH=/usr/local/netcdf-4.6.1/lib:/usr/local/cuda/lib64:/usr/local/lib64
                  MANPATH=:
               MODULEPATH=/etc/scl/modulefiles:/etc/scl/modulefiles:/usr/share/Modules/modulefil
                          es:/etc/modulefiles:/usr/share/modulefiles
                     PATH=/home/gtrojan/miniconda3/bin:/home/gtrojan/miniconda3/envs/spyder/bin:
                          /usr/share/Modules/bin:/usr/local/netcdf-4.6.1/bin:/usr/local/cuda/bin
                          :/usr/lib64/qt5/bin:/usr/local/bin:/usr/bin:/usr/sbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=1

     active environment : spyder
    active env location : /home/gtrojan/miniconda3/envs/spyder
            shell level : 2
       user config file : /home/gtrojan/.condarc
 populated config files : /home/gtrojan/.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.2
                          __glibc=2.30
       base environment : /home/gtrojan/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/gtrojan/miniconda3/pkgs
                          /home/gtrojan/.conda/pkgs
       envs directories : /home/gtrojan/miniconda3/envs
                          /home/gtrojan/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.3 Linux/5.3.14-300.fc31.x86_64 fedora/31 glibc/2.30
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.                                     
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/gtrojan/miniconda3/envs/spyder:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py38_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pip                       20.0.2                   py38_1    conda-forge
python                    3.8.1                h357f687_2    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                45.1.0                   py38_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
wheel                     0.34.2                   py38_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : spyder
    active env location : /home/gtrojan/miniconda3/envs/spyder
            shell level : 3
       user config file : /home/gtrojan/.condarc
 populated config files : /home/gtrojan/.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.2
                          __glibc=2.30
       base environment : /home/gtrojan/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/gtrojan/miniconda3/pkgs
                          /home/gtrojan/.conda/pkgs
       envs directories : /home/gtrojan/miniconda3/envs
                          /home/gtrojan/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.3 Linux/5.3.14-300.fc31.x86_64 fedora/31 glibc/2.30
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by ccordoba12** [comment]
I think you should name your env as `spyder` because that could confuse conda. Please use another name and try again.

**Comment by yt87** [comment]
It is not the name, I tried earlier to install in another conda environment. 
I cleaned up my bash environment to exclude local customisations. The error is now different and puzzling. 

```
$ conda create --name foo python=3.8 spyder
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                             

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
spyder -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|3.4.*']
python=3.8
spyder -> atomicwrites -> python[version='>=3.5']The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2

Note that strict channel priority may have removed packages required for satisfiability.
```

**Comment by yt87** [comment]
Follow up: I split installation into 2 steps (in the clean environment), the same as in my original report:
```
$ conda create --name foo python=3.8
$ conda activate foo
$ conda install spyder
```
Result is the same error as in the original report.

**Comment by yt87** [comment]
Final follow-up for today: the problem is with python-3.8 package. The same setps for 3.7 work as expected:
```
$ conda create --name bar python=3.7
$ conda activate bar
$ conda install spyder
```

**Comment by ccordoba12** [comment]
Yes, the problem is with Python 3.8. I think the stack is not ready for it.

Please try again in a couple of months.
